# Generated by Django 5.1.3 on 2024-12-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
